// <auto-generated />
namespace PhMS2dot1Domain.PhMS2dot1DomainContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialPhMS2dot1DomainBaseInfrastructer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialPhMS2dot1DomainBaseInfrastructer));
        
        string IMigrationMetadata.Id
        {
            get { return "201610130309023_InitialPhMS2dot1DomainBaseInfrastructer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
