// <auto-generated />
namespace PhMS2dot1Domain.PhMS2dot1DomainContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdatePhMS2dot1DomainDrugRecord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatePhMS2dot1DomainDrugRecord));
        
        string IMigrationMetadata.Id
        {
            get { return "201612121449254_UpdatePhMS2dot1DomainDrugRecord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
